import React, { useEffect } from 'react'

//css
import classes from "./Notes_select.module.css"

//redux hooks
import { useDispatch, useSelector } from "react-redux"

//redux action creators
import {submit_form} from "../../../../Store/Actions/0_submit_form_action"

export const Notes_select = props => {

    //-config
    const dispatch = useDispatch()//initialise the usedispatch hook
    
    //?selectors
    const response = useSelector(state => state.form.response)//grab the returned notes generated by the search string

    console.log(response)

    //!effects
    useEffect(() => {

        dispatch(submit_form({ search_string: props.search_string, user_id: "5eecd941331a770017a74e44" }, "search"))

    }, [props.search_string])

    console.log(props.search_string)

    return (

        <div className={classes.container}>

        </div>

    )

}

export default Notes_select
